version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis

  backend:
    image: ./backend/
    container_name: backend
    depends_on:
      - redis
    restart: always
    volumes:
      - ./backend/src/assets/:/app/src/assets/
    networks:
      - backend
    ports:
      - "8661:3001"

  frontend:
    image: ./frontend/
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "8660:80"

networks:
  backend:
    driver: bridge