version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: ./backend/
    container_name: backend
    depends_on:
      - redis
    restart: always
    volumes:
      - ./backend/src/assets/:/app/src/assets/
    ports:
      - "8661:3001"

  frontend:
    image: ./frontend/
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "8660:80"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    volumes:
        - ./mysql/data:/var/lib/mysql