version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose:
      - 6379
    networks:
      - bda

  backend:
    build: ./bda-backend/
    container_name: backend
    depends_on:
      - redis
      - mysql
    restart: always
    volumes:
      - ./bda-backend/src/assets/:/app/src/assets/
    environment:
      MYSQL_HOST: mysql
    ports:
      - "8661:3001"
    networks:
      - bda

  frontend:
    build: ./bda-frontend/
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "8660:80"
    networks:
      - bda

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "bda"
      MYSQL_USER: "bda"
      MYSQL_PASSWORD: "0ptic$$"
      MYSQL_ROOT_PASSWORD: "$$1rth1$$1$$aW3nDyS"
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - bda

networks:
  bda:
    driver: bridge